/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fpworkshop;

import org.junit.Test;

import java.math.BigDecimal;

import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;

public class CafeExample {

    @Test
    public void buyingCupOfCoffee(){
        var creditCard = new CreditCard();
        var cafe = new Cafe();

        Coffee cup = cafe.buyCoffee(creditCard);

        assertThat(cup, notNullValue());
    }

    class Cafe {
        Coffee buyCoffee(CreditCard creditCard) {
            var cup = new Coffee();

            creditCard.charge(cup.price);

            return cup;
        }
    }

    private class Coffee {
        BigDecimal price = new BigDecimal(1);
    }

    private class CreditCard {
        void charge(BigDecimal price) {
            try {
                Thread.sleep(5_000);
                if (Math.random() > 0.2) throw new IllegalStateException("The server does not respond");
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
