/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/5.1.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation("io.vavr:vavr:0.10.0")

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.1.0")
    testImplementation("org.hamcrest:hamcrest:2.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.1.0")

}

application {
    // Define the main class for the application
    mainClassName = "fpworkshop.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
