/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fpworkshop;

import java.math.BigDecimal;
import java.util.concurrent.CompletableFuture;

public class SomeClassWeDontNeed {

}
